### ISSUE TITLE
Run on ESP32-C3-32S Kit board

### ISSUE THREAD

**Issue by brookman** [fkohlgrueber/esp32c3-idf-led-example#1]
Hello @fkohlgrueber 

Thank you for providing this LED example. As a total beginner this is really helpful.

I am trying to get it running on my "[ESP-C3-32S-Kit ESP32 WiFi+Bluetooth Development Board](https://www.waveshare.com/esp-c3-32s-kit.htm)". I can build and flash fine but run into troubles when running. `espmonitor `gives me the following output:

```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x403d153e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x172c
load:0x403ce000,len:0x928
load:0x403d0000,len:0x2ce0
entry 0x403ce000
←[0;32mI (35) boot: ESP-IDF v4.4-dev-2825-gb63ec47238 2nd stage bootloader←[0m
←[0;32mI (35) boot: compile time 12:10:40←[0m
←[0;32mI (35) boot: chip revision: 3←[0m
←[0;32mI (38) boot_comm: chip revision: 3, min. bootloader chip revision: 0←[0m
←[0;32mI (45) boot.esp32c3: SPI Speed      : 80MHz←[0m
←[0;32mI (50) boot.esp32c3: SPI Mode       : DIO←[0m
←[0;32mI (55) boot.esp32c3: SPI Flash Size : 4MB←[0m
←[0;32mI (60) boot: Enabling RNG early entropy source...←[0m
←[0;32mI (65) boot: Partition Table:←[0m
←[0;32mI (69) boot: ## Label            Usage          Type ST Offset   Length←[0m
←[0;32mI (76) boot:  0 nvs              WiFi data        01 02 00009000 00006000←[0m
←[0;32mI (83) boot:  1 phy_init         RF data          01 01 0000f000 00001000←[0m
←[0;32mI (91) boot:  2 factory          factory app      00 00 00010000 003f0000←[0m
←[0;32mI (98) boot: End of partition table←[0m
←[0;32mI (102) boot_comm: chip revision: 3, min. application chip revision: 0←[0m
←[0;32mI (110) esp_image: segment 0: paddr=00010020 vaddr=3c030020 size=0bac8h ( 47816) map←[0m
←[0;32mI (125) esp_image: segment 1: paddr=0001baf0 vaddr=3fc8ae00 size=01be0h (  7136) load←[0m
←[0;32mI (128) esp_image: segment 2: paddr=0001d6d8 vaddr=40380000 size=02940h ( 10560) load←[0m
←[0;32mI (137) esp_image: segment 3: paddr=00020020 vaddr=42000020 size=263d0h (156624) map←[0m
←[0;32mI (167) esp_image: segment 4: paddr=000463f8 vaddr=40382940 size=08484h ( 33924) load←[0m
←[0;32mI (174) esp_image: segment 5: paddr=0004e884 vaddr=50000000 size=00010h (    16) load←[0m
←[0;31mE (174) esp_image: invalid segment length 0x7b4a←[0m
←[0;31mE (178) boot: Factory app partition is not bootable←[0m
```

I fear that the binary might be too large (debug is 9.8mb, release is 3.5mb) for my device, as it only has 2mb of flash. Running `espflash --board-info` gives me this:
```
Chip type:         ESP32-C3 (revision 3)
Crystal frequency: 40MHz
Flash size:        2MB
Features:          WiFi
MAC address:       ...
```
Which is for some reason not the same as `espmonitor`. (4MB vs 2MB, 80MHz vs 40MHz).

Do you think the binary size is the problem here?
I have already tried making the binary smaller by using some instructions from [min-sized-rust](https://github.com/johnthagen/min-sized-rust). Unfortunately this is not enough to bring it below 2mb.

Edit: After some tinkering I could bring down the ELF size to ~400kb by adding `strip = "symbols"` to my Cargo.toml. However now I'm getting a new error:
```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40382154
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x172c
load:0x403ce000,len:0x928
load:0x403d0000,len:0x2ce0
entry 0x403ce000
←[0;32mI (35) boot: ESP-IDF v4.4-dev-2825-gb63ec47238 2nd stage bootloader←[0m
←[0;32mI (35) boot: compile time 12:10:40←[0m
←[0;32mI (35) boot: chip revision: 3←[0m
←[0;32mI (38) boot_comm: chip revision: 3, min. bootloader chip revision: 0←[0m
←[0;32mI (45) boot.esp32c3: SPI Speed      : 80MHz←[0m
←[0;32mI (50) boot.esp32c3: SPI Mode       : DIO←[0m
←[0;32mI (55) boot.esp32c3: SPI Flash Size : 4MB←[0m
←[0;32mI (60) boot: Enabling RNG early entropy source...←[0m
←[0;32mI (65) boot: Partition Table:←[0m
←[0;32mI (69) boot: ## Label            Usage          Type ST Offset   Length←[0m
←[0;32mI (76) boot:  0 nvs              WiFi data        01 02 00009000 00006000←[0m
←[0;32mI (83) boot:  1 phy_init         RF data          01 01 0000f000 00001000←[0m
←[0;32mI (91) boot:  2 factory          factory app      00 00 00010000 003f0000←[0m
←[0;32mI (98) boot: End of partition table←[0m
←[0;32mI (102) boot_comm: chip revision: 3, min. application chip revision: 0←[0m
←[0;32mI (110) esp_image: segment 0: paddr=00010020 vaddr=3c020020 size=07798h ( 30616) map←[0m
←[0;32mI (123) esp_image: segment 1: paddr=000177c0 vaddr=3fc8a600 size=01b8ch (  7052) load←[0m
←[0;32mI (128) esp_image: segment 2: paddr=00019354 vaddr=40380000 size=06cc4h ( 27844) load←[0m
←[0;32mI (140) esp_image: segment 3: paddr=00020020 vaddr=42000020 size=1fb2ch (129836) map←[0m
←[0;32mI (163) esp_image: segment 4: paddr=0003fb54 vaddr=40386cc4 size=037ech ( 14316) load←[0m
←[0;32mI (166) esp_image: segment 5: paddr=00043348 vaddr=50000000 size=00010h (    16) load←[0m
←[0;32mI (172) boot: Loaded app from partition at offset 0x10000←[0m
←[0;32mI (175) boot: Disabling RNG early entropy source...←[0m
←[0;32mI (192) cpu_start: Pro cpu up.←[0m
←[0;32mI (204) cpu_start: Pro cpu start user code←[0m
←[0;32mI (204) cpu_start: cpu freq: 160000000←[0m
←[0;32mI (204) cpu_start: Application information:←[0m
←[0;32mI (207) cpu_start: Project name:     esp-idf←[0m
←[0;32mI (212) cpu_start: App version:      affc3f6-dirty←[0m
←[0;32mI (217) cpu_start: Compile time:     Nov 30 2021 17:43:53←[0m
←[0;32mI (223) cpu_start: ELF file SHA256:  0000000000000000...←[0m
←[0;32mI (229) cpu_start: ESP-IDF:          4.3.1←[0m
←[0;32mI (234) heap_init: Initializing. RAM available for dynamic allocation:←[0m
←[0;32mI (241) heap_init: At 3FC8D010 len 00032FF0 (203 KiB): DRAM←[0m
←[0;32mI (247) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM←[0m
←[0;32mI (254) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM←[0m
←[0;32mI (261) spi_flash: detected chip: generic←[0m
←[0;32mI (265) spi_flash: flash io: dio←[0m
←[0;31mE (269) spi_flash: Detected size(2048k) smaller than the size in the binary image header(4096k). Probe failed.←[0m
abort() was called at PC 0x4200de6d on core 0
Core  0 register dump:
MEPC    : 0x4038349c  RA      : 0x40383b52  SP      : 0x3fcde230  GP      : 0x3fc8ae00
TP      : 0x00000000  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x00000004  S1      : 0x3fcde294  A0      : 0x3fcde25c  A1      : 0x3fcde292
A2      : 0x00000000  A3      : 0x3fcde289  A4      : 0x00000001  A5      : 0x3fc8d000
A6      : 0x7a797877  A7      : 0x76757473  S2      : 0x3c022000  S3      : 0x3fc8cbc8
S4      : 0x42000020  S5      : 0x00020020  S6      : 0x00000000  S7      : 0x3fcd7000
S8      : 0x3c020020  S9      : 0x00010020  S10     : 0x00000006  S11     : 0x3fcde3cc
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
MHARTID : 0x00000000
Stack memory:
3fcde230: 0x00000006 0x00010020 0x3fcde290 0x403893c6 0x00000000 0x00020020 0x42000020 0x3fc8bbe8
3fcde250: 0x3fcde294 0x3fc8bc04 0x3fcde290 0x726f6261 0x20292874 0x20736177 0x6c6c6163 0x61206465
3fcde270: 0x43502074 0x34783020 0x64303032 0x20643665 0x63206e6f 0x2065726f 0x00000030 0x42000000
...
```

**Comment by fkohlgrueber** [comment]
I don't think that the size of the binary (I guess you're measuring the size of the elf file?!) is the problem here, but rather an alignment issue. Segments need to have 4-byte alignment if I remember correctly. I've seen the `invalid segment length` error too a couple of times and there's also some issues mentioning it (see [here](https://github.com/ivmarkov/rust-esp32-std-demo/issues/34) and [here](https://github.com/ivmarkov/rust-esp32-std-demo/issues/14)).

For me, using `esp-idf-sys`'s native build feature fixed the issue and I didn't have any problems afterwards. You can take a look at [rust-esp32-std-demo](https://github.com/ivmarkov/rust-esp32-std-demo), which is updated frequently. I think you should be able to get the example running by simply adding the native feature to esp-idf-sys and probably doing a clean build. 

I'll try to update this repo to use native build soon. Let me know if you still have issues.

**Comment by fkohlgrueber** [comment]
I've pushed an update that activates the native build (and updates dependencies). Let me know if it works for you.

**Comment by brookman** [comment]
Thank you very much! I could successfully build the project with the native feature. But only after setting the env var `ESP_IDF_INSTALL_DIR=path/to/my/.espressif`. The automatic esp-idf install fails.

Additionally I can only build the project in debug mode currently because of some path length limitation. So `cargo build` instead of `cargo build --release`.

The running binary produces this output:
```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x172c
load:0x403ce000,len:0x928
load:0x403d0000,len:0x2ce0
entry 0x403ce000
←[0;32mI (30) boot: ESP-IDF v4.4-dev-2825-gb63ec47238 2nd stage bootloader←[0m
←[0;32mI (30) boot: compile time 12:10:40←[0m
←[0;32mI (30) boot: chip revision: 3←[0m
←[0;32mI (33) boot_comm: chip revision: 3, min. bootloader chip revision: 0←[0m
←[0;32mI (40) boot.esp32c3: SPI Speed      : 80MHz←[0m
←[0;32mI (45) boot.esp32c3: SPI Mode       : DIO←[0m
←[0;32mI (50) boot.esp32c3: SPI Flash Size : 4MB←[0m
←[0;32mI (55) boot: Enabling RNG early entropy source...←[0m
←[0;32mI (60) boot: Partition Table:←[0m
←[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length←[0m
←[0;32mI (71) boot:  0 nvs              WiFi data        01 02 00009000 00006000←[0m
←[0;32mI (78) boot:  1 phy_init         RF data          01 01 0000f000 00001000←[0m
←[0;32mI (86) boot:  2 factory          factory app      00 00 00010000 003f0000←[0m
←[0;32mI (93) boot: End of partition table←[0m
←[0;32mI (98) boot_comm: chip revision: 3, min. application chip revision: 0←[0m
←[0;32mI (105) esp_image: segment 0: paddr=00010020 vaddr=3c030020 size=08700h ( 34560) map←[0m
←[0;32mI (118) esp_image: segment 1: paddr=00018728 vaddr=3fc8a400 size=00c6ch (  3180) load←[0m
←[0;32mI (122) esp_image: segment 2: paddr=0001939c vaddr=40380000 size=06c7ch ( 27772) load←[0m
←[0;32mI (135) esp_image: segment 3: paddr=00020020 vaddr=42000020 size=26130h (155952) map←[0m
←[0;32mI (162) esp_image: segment 4: paddr=00046158 vaddr=40386c7c size=036ach ( 13996) load←[0m
←[0;32mI (165) esp_image: segment 5: paddr=0004980c vaddr=50000000 size=00010h (    16) load←[0m
←[0;32mI (171) boot: Loaded app from partition at offset 0x10000←[0m
←[0;32mI (174) boot: Disabling RNG early entropy source...←[0m
←[0;32mI (191) cpu_start: Pro cpu up.←[0m
←[0;32mI (199) cpu_start: Pro cpu start user code←[0m
←[0;32mI (199) cpu_start: cpu freq: 160000000 Hz←[0m
←[0;32mI (199) cpu_start: Application information:←[0m
←[0;32mI (202) cpu_start: Project name:     libespidf←[0m
←[0;32mI (207) cpu_start: App version:      1←[0m
←[0;32mI (212) cpu_start: Compile time:     Nov 30 2021 21:40:16←[0m
←[0;32mI (218) cpu_start: ELF file SHA256:  0000000000000000...←[0m
←[0;32mI (224) cpu_start: ESP-IDF:          68cf4ef←[0m
←[0;32mI (229) heap_init: Initializing. RAM available for dynamic allocation:←[0m
←[0;32mI (236) heap_init: At 3FC8BFC0 len 00034040 (208 KiB): DRAM←[0m
←[0;32mI (242) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM←[0m
←[0;32mI (249) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM←[0m
←[0;32mI (256) spi_flash: detected chip: generic←[0m
←[0;32mI (260) spi_flash: flash io: dio←[0m
←[0;31mE (264) spi_flash: Detected size(2048k) smaller than the size in the binary image header(4096k). Probe failed.←[0m
←[0;32mI (275) sleep: Configure to isolate all GPIO pins in sleep state←[0m
←[0;32mI (281) sleep: Enable automatic switching of GPIO sleep configuration←[0m
←[0;32mI (289) cpu_start: Starting scheduler.←[0m
```
There is still a warning (?) related to the flash size. I'm not sure if it matters but I can make it go away by providing espflash with a custom bootloader and partition table.
For the record: I got the bootloader.bin by building a hello_world project from the esp-idf like this:
```
idf.py set-target esp32c3
idf.py menuconfig
idf.py build
```
In the menuconfig step I configured the flash size to 2MB and disabled auto-detect. Then my partition file looks like this:
```
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs,      data, nvs,      0x9000,  0x6000,
phy_init, data, phy,      0xf000,  0x1000,
factory,  app,  factory,  0x10000,  1M,
```

Flash with:
```
espflash --bootloader bootloader.bin --partition-table table.csv COM3 target/riscv32imc-esp-espidf/debug/esp32c3-idf-led-example
```

Edit: Got it working!

**Comment by javiser** [comment]
Thanks @brookman for the detailed explanation! I was using this example as well and got similar problems, which I could solve with your hints. I also have the exact same board you have but I don't get the LED to run. I looked into the schematics and it would seem that this board does not use a WS2812 led but three individual pins:
![led](https://user-images.githubusercontent.com/75809109/149551403-0569caae-2d65-492c-bc35-2c4b0b0bb2ab.png)
(source: https://www.waveshare.com/w/upload/4/46/Nodemcu-esp-c3-32s-kit-schematics.pdf)
Did you adjust your example as well accordingly?

**Comment by javiser** [comment]
Furthermore, I just noticed that the code may not be running at all, since I don't see any info messages within the program output after the `I (269) cpu_start: Starting scheduler.` message. Any hint would be quite appreciated.

**Comment by fkohlgrueber** [comment]
@javiser seems like I broke the logging output during one of the updates. I also don't get any output after the `Starting scheduler` message. I've pushed an update that should fix the logging.

**Comment by fkohlgrueber** [comment]
Regarding the LED: if your dev board doesn't have a WS2812 LED but uses three separate pins, you can simply drive a high signal on one of them to see whether the LED works.

**Comment by javiser** [comment]
> @javiser seems like I broke the logging output during one of the updates. I also don't get any output after the `Starting scheduler` message. I've pushed an update that should fix the logging.

Yes, that fixes the problem!

**Comment by javiser** [comment]
> Regarding the LED: if your dev board doesn't have a WS2812 LED but uses three separate pins, you can simply drive a high signal on one of them to see whether the LED works.

Yes, I thought about that. But I am trying still to find out how to do that. I have been playing around with Rust and a couple of boards during the last couple of weeks and it seems that all the solutions and examples are different :disappointed:

**Comment by fkohlgrueber** [comment]
Embedded Rust is still evolving, that's why examples might look different. In general, you'll want to use a hardware abstraction layer (hal) crate for your board. For the esp32c3, you can use `esp-idf-hal`. Hal crates provide one layer of abstraction on top of the raw device specific memory addresses you'd otherwise need program yourself. There's another crate called `embedded-hal` which contains traits for common peripherals found on microcontrollers. `embedded-hal` provides traits that are then implemented by hal crates for boards (e.g. `esp-idf-hal`).

Blinking your on-board led should be as simple as toggling the output of one of the gpio pins. For example, if you want to toggle gpio pin 4, you'd need get the corresponding object from the hal crate. This object has the type Gpio4, which implements `embedded-hal`s `OutputPin` trait. You can then simply call `set_high()` and `set_low()` on that object to toggle the output.

Here's a diff showing how this repo's code can be modified to make it happen:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index b1fa713..e1c18a7 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -11,6 +11,8 @@ anyhow = {version = "1", features = ["backtrace"]}
 log = "0.4"
 esp-idf-sys = { version = "0.30", features = ["binstart", "native"] }
 esp-idf-svc = "0.36.2"
+esp-idf-hal = "0.32.3"
+embedded-hal = "0.2.6"
 
 [build-dependencies]
 embuild = "0.28"
diff --git a/src/main.rs b/src/main.rs
index 187434f..137dfdd 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -6,6 +6,9 @@ use std::thread;
 use anyhow::*;
 use log::*;
 
+use esp_idf_hal::peripherals::Peripherals;
+use embedded_hal::digital::v2::OutputPin;
+
 use esp_idf_sys;
 
 use crate::led_strip::Led;
@@ -16,6 +19,20 @@ fn main() -> Result<()> {
     // Bind the log crate to the ESP Logging facilities
     esp_idf_svc::log::EspLogger::initialize_default();
 
+    // simple blinky output pin
+    let peripherals = Peripherals::take().unwrap();
+    let pins = peripherals.pins;
+
+    let mut led = pins.gpio4.into_output()?;
+
+    loop {
+        led.set_high()?;
+        thread::sleep(Duration::from_millis(1000));
+        led.set_low()?;
+        thread::sleep(Duration::from_millis(1000));
+    }
+
+    /*
     info!("Let's use the esp32c3 rgb led!");
 
     let mut led = Led::new(
@@ -46,4 +63,5 @@ fn main() -> Result<()> {
         led.fade_to(L, L, H, NUM_STEPS, DURATION)?;
         led.fade_to(H, L, H, NUM_STEPS, DURATION)?;
     }
+    */
 }

```

Let me know if that helps.

**Comment by javiser** [comment]
Wow! Awesome! So many thanks for the help! That worked like a charm! I still need to dig in the specs for that board, I tried with GPIO18 and that activated a yellow built-in led and GPIO19 activated the white one. I was used to the fantastic documentation from Adafruit and this one is not that nice.

Thanks again for your help!

**Comment by fkohlgrueber** [comment]
Yeah, that's all still pretty much work in progress. `esp-idf-hal` unfortunately also doesn't have docs available on docs.rs, but you can build them locally using `cargo doc --open`. You can also join the esp-rs matrix group and ask for help there: https://matrix.to/#/#esp-rs:matrix.org
